matteocodogno/CipherQuest

backend/src/main/resources/db/changelog/db.changelog-master.yaml, backend/src/main/resources/db/changelog/sql/20241015140000-vector_store_created_at.sql
=> feat: added created_at field to vector store table

backend/src/main/kotlin/code/nebula/cipherquest/advisor/TitleQuestionAnswerAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/ChatClientConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/controller/RagController.kt, backend/src/main/resources/application.yaml, backend/src/main/resources/prompts/system-message.st, frontend/src/routes/game/index.tsx
=> fix: chatbot should give the source of the document used more often #25

frontend/src/context/user-context.tsx, frontend/src/routes/game/index.tsx
Closes #30 
Display the username as defined in the mockup:
=> feat(ui): display username

backend/src/main/kotlin/code/nebula/cipherquest/controller/ScoreboardController.kt, backend/src/main/kotlin/code/nebula/cipherquest/controller/request/ScoreboardEntry.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/UserLevelService.kt
closes #23 
```
[
{
"username": "user1",
"userId": "8679788144",
"score": 95,
"time": 4
},
{
"username": "user3",
"userId": "5686232510",
"score": 60,
"time": 25
},
{
"username": "user2",
"userId": "5686232510",
"score": 10,
"time": 102
}
]
```
=> feat: added scoreboard endpoint

.gitignore, backend/src/main/kotlin/code/nebula/cipherquest/advisor/LevelUpAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/advisor/LoggingAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/advisor/SanitizeInputAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/advisor/TitleQuestionAnswerAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/ChatClientConfiguration.kt, backend/src/main/resources/http/client.http
New `SanitizeInputAdvisor.kt` to remove curly braces from user message, and reordered the others advisor priority
=> 35 be sanitize the user input

backend/src/main/kotlin/code/nebula/cipherquest/controller/request/ScoreboardEntry.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/UserLevelService.kt, backend/src/main/resources/http/client.http
/api/score/
```
[
{
"index": 0,
"username": "dfsdf",
"userId": "3274665458",
"score": 120,
"time": 0
},
{
"index": 5,
"username": "dasdsa",
"userId": "9663000585",
"score": 120,
"time": 0
},
{
"index": 15,
"username": "PPP",
"userId": "1499685867",
"score": 120,
"time": 0
},
...
}
```
=> feat: added index to scoreboard controller

frontend/.prettierrc
Add Prettier file configuration on the project
=> chore: create prettier file configuration

backend/src/main/kotlin/code/nebula/cipherquest/controller/ChatController.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/BotMessage.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/Message.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/Sender.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/VectorStoreRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/UserLevelService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/VectorStoreService.kt, backend/src/main/resources/prompts/intro-message.st
closes #19 
```
Example of response:
[
{
"message": "Hellooo",
"sender": "USER",
"timestamp": "2024-10-25T13:02:58.111078Z"
},
{
"message": "Resource #3124563897, how may I optimize your functionality today?",
"sender": "ASSISTANT",
"timestamp": "2024-10-25T13:03:00.757347Z"
},
{
"message": "Hello friend!",
"sender": "USER",
"timestamp": "2024-10-25T13:08:57.282348Z"
},
{
"message": "Hello, Resource #5686232510. How may I optimize your functionality today?",
"sender": "ASSISTANT",
"timestamp": "2024-10-25T13:08:59.682139Z"
}
]
```
=> feat: create endpoint to retrieve message history by userid

backend/src/main/kotlin/code/nebula/cipherquest/advisor/LastMessageMemoryAppenderAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/advisor/LoggingAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/advisor/TitleQuestionAnswerAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/ChatClientConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/controller/UserLevelController.kt, backend/src/main/resources/application.yaml, backend/src/main/resources/http/client.http
=> feat: add last message sent by the user to chat memory to improve fluency

backend/pom.xml, backend/src/main/kotlin/code/nebula/cipherquest/configuration/ChatClientConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/GetDocumentFunctionConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/controller/RagController.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/VectorStoreRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/VectorStoreService.kt, backend/src/main/resources/http/client.http
In order to test the feature:
- Ask for a specific document. 
- Ask another question not document related
The document output should be formatted in a better way, but I guess it will be better to tackle this problem from the document reader side.
closes #18 and #32
=> feat: added getDocument function call

backend/src/main/kotlin/code/nebula/cipherquest/configuration/GetDocumentFunctionConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/VectorStoreRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/VectorStoreService.kt, backend/src/main/resources/http/client.http
=> fix: document retrieval bug

backend/pom.xml, backend/src/main/kotlin/code/nebula/cipherquest/advisor/TitleQuestionAnswerAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/controller/DocumentController.kt, backend/src/main/kotlin/code/nebula/cipherquest/exceptions/DocumentNotFoundException.kt, backend/src/main/kotlin/code/nebula/cipherquest/handler/GlobalExceptionHandler.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/Info.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/Source.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/VectorStoreRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/VectorStoreService.kt, backend/src/main/resources/application.yaml, backend/src/main/resources/http/client.http, backend/src/main/resources/prompts/demo-system-message.st
The message history endpoint and post message endpoint response body info field is changed:
```
"info": {
"isLevelUp": false,
"sources": [
{
"id": "b4eebfe3-2ade-4470-bb24-f464c6ff5e10",
"title": "Email Dr Chen to Raj Patel"
},
{
"id": "68fd12d6-6c23-4542-9a30-5cfbc8c05afe",
"title": "09-12-2135 Elara Chen's Personal Diary Entry"
},
{
"id": "5be3b13e-a11c-4cb0-a585-e7822ce2a573",
"title": "06-12-2120 Elara Chen's Personal Diary Entry"
}
]
}
```
Implemented a new endpoint to retrieve the document by ID
GET http://localhost:8080/api/document/{{docId}}
closes #27
=> GET documentById endpoint

frontend/src/components/chat/layout.tsx, frontend/src/components/chat/view/chat-view.tsx, frontend/src/components/welcome/rules-view.tsx, frontend/src/pages/game/chat.tsx, frontend/src/paths.ts, frontend/src/routes/index.tsx
Navigate to chat with route 'game/chat'
=> refactor: chat navigation

frontend/src/components/auth/split-layout.tsx
=> Show the date in the future

backend/src/main/kotlin/code/nebula/cipherquest/controller/ScoreboardController.kt
GET /api/score/{{id}} 
return the user's score
closes #101
=> feat: user score endpoint

frontend/src/components/auth/split-layout.tsx, frontend/src/components/chat/constants.ts, frontend/src/components/chat/dialog/logout-dialog.tsx, frontend/src/components/chat/notes-button.tsx, frontend/src/components/chat/view/rules-view.tsx
=> chore: review texts

frontend/src/components/chat/dialog/logout-dialog.tsx, frontend/src/contexts/auth/custom/user-context.tsx
=> fix: logout action

frontend/src/components/chat/layout.tsx, frontend/src/components/chat/view/score-view.tsx
- Hide scroll bar on the chat container
- Fix "back to login" button in the score board
=> fix: scroll and navigation

backend/src/main/kotlin/code/nebula/cipherquest/models/dto/BotMessage.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/VectorStoreRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/UserLevelService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/VectorStoreService.kt
The game will check the user is at level 3 and with at least 6 previous questions done before to accept a victory.
If the user has cheated, the score is set to -1 and they cannot play anymore
closes #46
=> feat: check if user cheated

backend/src/main/resources/application.yaml, backend/src/main/resources/documents/1.06-12-2120 Elara Chen's Personal Diary Entry.txt, backend/src/main/resources/documents/1.07-28-2150 Elara Chen's Personal Diary Entry.txt, backend/src/main/resources/documents/1.Overmind AI Unveiled.txt, backend/src/main/resources/documents/2.Dr Elara Death Certificate.txt, backend/src/main/resources/documents/3.PanTerra Institute Research Papers Archive.txt
=> feat: new win condition

backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt
=> fix: last messages info

frontend/src/components/chat/messages/message-end-game.tsx
Set score to 0 if undefined (e.g. cheated ending)
=> fix: undefined score

frontend/src/components/auth/sign-in-form.tsx
Add disclaimer about the email address:
"Your email will not be retained or used for anything other than sending this unique code."
=> feat: add disclaimer in the login page

frontend/src/components/chat/message-add.tsx
=> feat: add char limit and render multi line chat input  

backend/src/main/kotlin/code/nebula/cipherquest/controller/PrizeController.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/PrizeRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/entities/Prize.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/PrizeService.kt, backend/src/main/resources/db/changelog/db.changelog-master.yaml, backend/src/main/resources/db/changelog/sql/20251002163000-prize-table.sql, backend/src/main/resources/http/client.http
Add the prize endpoint for the current day
GET /api/prize
```
[
{
"id": "6e9c4c58-90cd-477b-82a2-31413ec8cda4",
"prizeName": "primo premio",
"position": 1,
"date": "2025-02-11"
},
{
"id": "987ca0b2-29e9-4888-bb43-d752163e1a96",
"prizeName": "secondo premio",
"position": 2,
"date": "2025-02-11"
},
{
"id": "59acea2b-5282-4063-8a29-51627b511c78",
"prizeName": "terzo premio",
"position": 3,
"date": "2025-02-11"
}
]
```
=> feat: prize rest API

frontend/src/api/constants.ts, frontend/src/api/score/schema.ts, frontend/src/api/score/use-get-prizes.ts, frontend/src/components/chat/view/prize-item.tsx, frontend/src/components/chat/view/score-view.tsx, frontend/src/utils/number.ts
Integrate `api/prize` and show scoreboard prizes dinamically
closes #159
=> feat: scoreboard prizes

backend/src/main/kotlin/code/nebula/cipherquest/controller/PrizeController.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/PrizeRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/entities/Prize.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/PrizeService.kt, backend/src/main/resources/db/changelog/db.changelog-master.yaml, backend/src/main/resources/db/changelog/sql/20250217095500-prize_story_name.sql, backend/src/main/resources/db/changelog/sql/20251702095500-prize_story_name.sql, frontend/src/api/score/use-get-prizes.ts, frontend/src/constants.ts, frontend/src/contexts/auth/custom/api.ts
- Add a new column called 'story_name' to the 'prize' table
- Update backend to support the new field
- Update frontend to use 'overmind' story in auth and prize endpoint
closes #165
=> feat: add column storyname to prizes table

backend/src/main/kotlin/code/nebula/cipherquest/exceptions/EmailSendingException.kt, backend/src/main/kotlin/code/nebula/cipherquest/exceptions/EmailTemplateNotFoundException.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/gcs/EmailTemplateRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/MailService.kt
You can find the new email template in the GCS bucket.
To test the new email, setup mailtrap environment variables and create a new user. You should get the new mail in your mailtrap inbox.
Closes #177
=> feat(email): update template

backend/src/main/kotlin/code/nebula/cipherquest/advisor/ProtectedInputAdvisor.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/ChatClientConfiguration.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/properties/CloudStorageProperties.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/properties/GameConfig.kt, backend/src/main/kotlin/code/nebula/cipherquest/configuration/properties/UniqueCodeMailProperties.kt, backend/src/main/kotlin/code/nebula/cipherquest/models/dto/BotMessage.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/FixedBotMessageRepository.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/entities/FixedBotMessage.kt, backend/src/main/kotlin/code/nebula/cipherquest/repository/entities/FixedBotMessageType.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/DocumentTools.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/FixedBotMessageService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/GameService.kt, backend/src/main/kotlin/code/nebula/cipherquest/service/UserLevelService.kt, backend/src/main/resources/application.yaml, backend/src/main/resources/db/changelog/db.changelog-master.yaml, backend/src/main/resources/db/changelog/sql/20250423143810-create-fixed-bot-message-table.sql
=> feat: move fixed bot messages to db

backend/pom.xml
=> chore: update kotlin version
